### ISSUE TITLE
Client Issue

### ISSUE THREAD

**Issue by NicoTravassos** [mavanmanen/Paper#1]
Hi there can you please give me the ability to connect to any irc client not just paper... also client is rather buggy

**Comment by mavanmanen** [comment]
Hello Nico, when you say you want to connect to any irc client besides Paper what exactly do you mean?
Also, I am fully aware the client is still very buggy, it's not ready for public testing yet.

**Comment by NicoTravassos** [comment]
Sorry What i mean is can you give me the ability to connect to any server not just paper because at the moment i can only connect to paper server.

**Comment by mavanmanen** [comment]
Currently the client does not have this ability, but you can download the source and modify it to suit your needs, shouldn't be hard because in the source the back-end and front-end are separate.

**Comment by NicoTravassos** [comment]
Okay thanks
